import { WorkshopAnalytics } from '@/lib/workshopAnalytics';

type ReportOptions = {
  reportTitle: string;
  includeRecommendations: boolean;
  generatedBy?: string;
};

function num(value: number) {
  return Number.isFinite(value) ? value : 0;
}

export function generateWorkshopAnalyticsReport(
  analytics: WorkshopAnalytics,
  meta: { totalCustomers: number; totalJobs: number; totalMechanics: number },
  options: ReportOptions
) {
  const now = new Date();
  const reportHeader = [
    options.reportTitle || 'Workshop Analytics Report',
    `Generated on: ${now.toLocaleString('en-IN')}`,
    options.generatedBy ? `Generated by: ${options.generatedBy}` : '',
  ].filter(Boolean);

  const lines: string[] = [];
  lines.push(...reportHeader);
  lines.push('');
  lines.push('=== Executive Summary ===');
  lines.push(`Total Revenue: INR ${Math.round(num(analytics.totalRevenue)).toLocaleString('en-IN')}`);
  lines.push(`Completed Jobs: ${analytics.completedJobs}`);
  lines.push(`Open Jobs: ${analytics.activeJobs}`);
  lines.push(`Completion Rate: ${analytics.completionRate.toFixed(1)}%`);
  lines.push(`Average Turnaround Time: ${analytics.avgTurnaroundHours.toFixed(1)} hours`);
  lines.push(`Repeat Customer Rate: ${analytics.repeatCustomerRate.toFixed(1)}%`);
  lines.push('');

  lines.push('=== Financial Performance ===');
  lines.push(`Monthly Revenue: INR ${Math.round(num(analytics.monthlyRevenue)).toLocaleString('en-IN')}`);
  lines.push(`Monthly Revenue Growth: ${analytics.monthlyRevenueGrowth.toFixed(1)}%`);
  lines.push(`Average Ticket Size: INR ${Math.round(num(analytics.avgTicket)).toLocaleString('en-IN')}`);
  lines.push(`Pipeline Value: INR ${Math.round(num(analytics.estimatedPipelineValue)).toLocaleString('en-IN')}`);
  lines.push(`Revenue Realization: ${analytics.realizationRate.toFixed(1)}%`);
  lines.push('');

  lines.push('=== Operations Performance ===');
  lines.push(`Pending Jobs: ${analytics.pendingJobs}`);
  lines.push(`Waiting Parts Jobs: ${analytics.waitingPartsJobs}`);
  lines.push(`Jobs Completed within 48 Hours: ${analytics.jobsCompletedWithin48hRate.toFixed(1)}%`);
  lines.push(`Top Mechanic: ${analytics.topMechanic}`);
  lines.push('');

  lines.push('=== Repair Mix ===');
  if (analytics.repairTypes.length === 0) {
    lines.push('No repair mix data available.');
  } else {
    analytics.repairTypes.forEach((item) => {
      lines.push(`- ${item.type}: ${item.count} jobs`);
    });
  }
  lines.push('');

  lines.push('=== Team Performance ===');
  if (analytics.mechanicPerformance.length === 0) {
    lines.push('No mechanic performance data available.');
  } else {
    analytics.mechanicPerformance.slice(0, 5).forEach((m, idx) => {
      lines.push(
        `${idx + 1}. ${m.mechanicName} | Completed: ${m.completedJobs} | Revenue: INR ${Math.round(num(m.revenue)).toLocaleString('en-IN')} | TAT: ${m.avgTurnaroundHours.toFixed(1)}h | Active: ${m.activeJobs}`
      );
    });
  }
  lines.push('');

  lines.push('=== Data Coverage ===');
  lines.push(`Total Jobs in Scope: ${meta.totalJobs}`);
  lines.push(`Total Customers in Scope: ${meta.totalCustomers}`);
  lines.push(`Total Mechanics in Scope: ${meta.totalMechanics}`);
  lines.push('');

  if (options.includeRecommendations) {
    lines.push('=== Recommendations ===');

    if (analytics.waitingPartsJobs >= 3) {
      lines.push('- Inventory risk detected: reduce waiting-parts queue with min stock and fast reorder thresholds.');
    }
    if (analytics.jobsCompletedWithin48hRate < 50) {
      lines.push('- Improve fast-turnaround process: prioritize high-frequency repairs with quick-bay workflow.');
    }
    if (analytics.realizationRate < 90) {
      lines.push('- Revenue realization is low: review estimate discipline and job closure billing checks.');
    }
    if (analytics.repeatCustomerRate < 40) {
      lines.push('- Customer retention opportunity: automate reminders and follow-up service campaigns.');
    }
    if (analytics.avgTurnaroundHours > 72) {
      lines.push('- Turnaround time is high: split heavy jobs by technician specialty and monitor handoff delays.');
    }

    if (
      analytics.waitingPartsJobs < 3 &&
      analytics.jobsCompletedWithin48hRate >= 50 &&
      analytics.realizationRate >= 90 &&
      analytics.repeatCustomerRate >= 40 &&
      analytics.avgTurnaroundHours <= 72
    ) {
      lines.push('- Overall workshop performance is healthy. Continue current operational standards and weekly review cadence.');
    }
  }

  return lines.join('\n');
}
